### PR TITLE
Allow starting from LATEST position

### PR DESCRIPTION
**Pull request by dcelasun**
This implements support for `ShardIteratorTypeLatest`. By setting `SequenceNumber` in DynamoDB to `LATEST`, consumers can start with the latest records in the stream.

### CODE REVIEW

**Comment by dcelasun** [comment]
@GarethLewin any chance you or someone else can take a look at this?

**Comment by garethlewin** [comment]
(Merged master into this branch to get the update Travis CI changes.)

**Comment by garethlewin** [comment]
@dcelasun So what is the workflow you propose for this, manually modifying the entries in the table? 

I have considered adding a config flag to start from latest, but I'm not sure if that achieves your goal since maybe you want to do this only for specific shards?

**Comment by dcelasun** [comment]
> manually modifying the entries in the table?

Yes, which also works for `TRIM_HORIZON`.

> maybe you want to do this only for specific shards?

Indeed, it's very useful for debugging when you are only interested in a single shard and you don't care about past events.

**Review by garethlewin — APPROVED** [review]

**Pull request merged**
